app/blog/routes.py
""" ROUTES FOR BLOG """
#pylint: disable=E0401
from flask import (
    render_template,
    Blueprint,
    flash,
    request,
    url_for,
    session, 
    

)



from flask_login import(
    current_user,
    login_required
)
from app.blog_form import BlogPostForm




blog_blueprint= Blueprint(
    "blog",
    __name__,
    template_folder="templates",
)
@blog_blueprint.route('/blog', methods=['GET', 'POST'])
@login_required
def blog():
    """ BLOG PAGE """
    form = BlogPostForm()
    if form.validate_on_submit():
        # Process the submitted code
        flash('Code submitted successfully!')
        # With HTMX, you might return partial HTML here
    user_name = get_username()
    is_authenticated = current_user.is_authenticated
    close = session['history'][-1]
    print(f"Is Authenticated: {is_authenticated}")
    return render_template('blog.jinja2', user_name=user_name,
                            form=form,
                            is_authenticated=is_authenticated,
                          )

@blog_blueprint.route('/feed', methods=['GET', 'POST'])
def feed():
    """ DYNAMIC DISPLAY """
    is_authenticated = current_user.is_authenticated
    close = session['history'][-1]
    missing_img = url_for('static', filename='src/images/missing_img.svg')
    return render_template('feed.jinja2',
                           is_authenticated=is_authenticated,
                           missing_img=missing_img,
                          )

@blog_blueprint.before_request
def track_history():
    if 'history' not in session:
        session['history'] = []
    session['history'].append(request.url)
    if len(session['history']) > 10:  # Limit history length
        session['history'].pop(0)

def get_username():
    """ Get Username """
    if current_user.is_authenticated:
        user_name = current_user.name
    else:
        user_name = "Guest"

    return user_name

def svg_github():
    """ DYNAMIC MENU """
    with open('app/home/img/github.svg', 'r',  encoding="utf-8") as file:
        svg = file.read()

    return svg

app/blog/templates/blog.jinja2
{% extends "blog_layout.jinja2" %}
{% block layout %}
    <div id="blog-container">
        {% include "/cms_blog.jinja2" %}
    </div>
{% endblock %}

app/blog/templates/blog_layout.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Datakiin</title>
    <meta name="Datakiin" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Place the first <script> tag in your HTML's <head> -->
    {% assets 'css' %}
      <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}

    
</head>
<body class="overflow-hidden h-screen">
  <header class="bg-black text-white py-6">
        <div class="container text-center">
            <h1 class="text-5xl font-bold tracking-tighter">DATAKIIN</h1>
        </div>
    </header>
    
    <nav>
        {% include "/nav_blog.jinja2" %}
    </nav>

    <div class="container overflow-auto h-[60vh]" id="hero">
        {% block layout %}{% endblock %}
    </div>



    <footer class="text-center mt-3">
        <p>Get in touch at <a href="mailto:jon.gracias@gmail.com" class="text-blue-500">jon.gracias@gmail.com</a></p>
        <a href="https://github.com/datakiin-core" class="inline-block mt-2" >
        GITHUB
        </a>
        |
        <a href="https://www.linkedin.com/in/jonathan-gracias-perez-b7577656" class="inline-block mt-2">
        LINKEDIN
        </a>
        |
        <a href="/phone" class="inline-block mt-2">
        PHONE
        </a>
    </footer>

  {% assets "js_home" %}
      <script type="text/javascript" src="{{ ASSET_URL }}"></script>
  {% endassets %}
</body>
</html>

app/blog/templates/cms_blog.jinja2
<div>
    <h1 class="text-2xl font-bold ">New Post</h1>
    <form method="POST" action="{{ url_for('blog.blog') }}" hx-post="{{ url_for('blog.blog') }}" hx-target="#post-list" hx-swap="outerHTML">
        {{ form.hidden_tag() }}
        <div class="mb-2">
        {{ form.body(class="form-textarea w-full h-32 p-4 text-lg border border-gray-300 rounded-lg focus:border-blue-500 focus:ring focus:ring-blue-200") }}

        </div>

        <div>
        {{ form.submit(class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mb-2 rounded focus:outline-none focus:shadow-outline") }}
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Edit</button>
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Save</button>
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Delete</button>
        </div>
    </form>
</div>
    

app/blog/templates/feed.jinja2
{% extends "blog_layout.jinja2" %}
{% block layout %}
    <div id="feed">
        <button class="article-card">
            <!-- Large Picture -->
            <div class="w-full">
                <img class="w-full h-auto" src={{missing_img}} alt="Article Image">
            </div>
            <!-- Title Bar -->
            <div class="bg-gray-100 p-4">
                <h1 class="text-6xl">Blog</h1>
                <a class="text-base md:text-lg lg:text-xl font-normal text-gray-700 dark:text-gray-300 leading-relaxed my-4 text-right block" href="/blog">Share</a>
            </div>

            <!-- Final Bar with Author and Share Button -->
            <div class="flex justify-between items-center bg-gray-200 p-4">
                <p class="text-base md:text-lg font-normal text-gray-700">Author</p>
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    Share
                </button>
            </div>
        </button>


    </div>
{% endblock %}

app/blog/templates/nav_blog.jinja2
<div class="navbar" id="nav">
    <div class="text-left">
        
    </div>

    {# Redunancy is important to stop links from loading - prevents nav flashing #}
    <div class="sm:block hidden" id="right-side-large">
        <div class="flex justify-between items-center">
            <div class="text-left" id="links">
            <a class="link-gray" href="/feed">Feed</a>
            <a class="link-gray" href="/blog">Blog</a>
            <a class="link-gray" href="/projects">Exit</a>
            </div>
            <div class="link-gray text-right block" id="user_menu"
                hx-get="/layout?menu=user_menu"
                hx-target="#links"
                hx-swap="innerHTML"
                onclick="toggleButtons('user_menu', 'close_user_menu')">
                User Menu
            </div>
            <div class="link-gray text-right hidden" id="close_user_menu"
                hx-get="/layout?menu=blog"
                hx-target="#links"
                hx-swap="innerHTML"
                onclick="toggleButtons('close_user_menu', 'user_menu')">
                Close
            </div>
        </div>
    </div>

    <div class="sm:hidden block" id="right-side-small">
        <div class="link-gray text-right block" id="mobile_menu"
            hx-get="/layout?menu=blog_mobile"
            hx-target="#hero"
            hx-swap="innerHTML"
            onclick="toggleButtons('mobile_menu', 'close_mobile_menu')">
            Menu
        </div>
        <a class="link-gray text-right hidden" id="close_mobile_menu"  href="/close">
            Close
        </a>
    </div>
</div>