app/home/routes.py
""" ROUTES FOR HOME """
#pylint: disable=E0401
from flask import (
    render_template,
    Blueprint,
    request,
    url_for,
    session
)

from flask_login import(
    current_user
)

home_blueprint= Blueprint(
    "home",
    __name__,
    template_folder="templates",
    static_folder="static",
)

@home_blueprint.route('/', methods=['GET', 'POST'])
def home():
    """ DYNAMIC DISPLAY """
    print(f"This is {request.path}")
    is_authenticated = current_user.is_authenticated
    missing_img = url_for('static', filename='src/images/missing_img.svg')
    hist = ', '.join(session['history'])
    print(f"History: {hist}")
    return render_template('home.jinja2',
                           is_authenticated=is_authenticated,
                           missing_img=missing_img)

@home_blueprint.errorhandler(404)
def page_not_found(e):
    # You can use a different template for 404 errors if you prefer
    return render_template('404.jinja2'), 404

@home_blueprint.before_request
def track_history():
    if 'history' not in session:
        session['history'] = []
    session['history'].append(request.url)
    if len(session['history']) > 10:  # Limit history length
        session['history'].pop(0)

def get_username():
    """ Get Username """
    if current_user.is_authenticated:
        user_name = current_user.name
    else:
        user_name = "Guest"

    return user_name

def svg_github():
    """ DYNAMIC MENU """
    with open('app/home/img/github.svg', 'r',  encoding="utf-8") as file:
        svg = file.read()

    return svg

app/home/templates/404.jinja2
{% extends "home_layout.jinja2" %}
{% block title %}
Error Page
{% endblock %}

{% block layout %}
<div id="error">
    <h1>Error Occurred</h1>
    <p>Sorry, an unexpected error has occurred.</p>
    <p>Please try again later or contact support if the problem persists.</p>
    
    <!-- Optional: Display error details if available -->
    {% if error_message %}
        <div class="error-details">
            <p><strong>Error Details:</strong>404</p>
        </div>
    {% endif %}

    <!-- Optional: Link to go back to home page or previous page -->
    <p><a class="link-gray" href="{{ url_for('home.home') }}">Go to Home Page</a></p>
</div>
{% endblock %}

app/home/templates/about.jinja2
{% extends "home_layout.jinja2" %}

{% block layout %}
<div  id="about">
        <header class="text-left my-2">
            <h1 class="text-4xl font-bold">Jonathan Gracias</h1>
            <p class="text-xl mt-2">Software Engineer</p>
        </header>

        <section>
            <h2 class="text-3xl font-semibold mb-4">About Me</h2>
            <p>I am a highly skilled and motivated Web Developer with a strong background in various programming languages and frameworks. My expertise lies in HTML, JavaScript, CSS, Python, and Java, and I have a special preference for working with the Flask, HTMX, and Tailwind stack. I find joy in backend programming and have professional experience in developing and maintaining WordPress sites.</p>
        </section>

        <section class="mt-8">
            <h2 class="text-3xl font-semibold mb-4">Skills</h2>
            <ul class="list-disc pl-5">
                <li>HTML, JavaScript, CSS</li>
                <li>Python, Java</li>
                <li>Flask, HTMX, Tailwind</li>
                <li>WordPress Development</li>
                <li>Backend Programming</li>
            </ul>
        </section>
</div>
{% endblock %}

app/home/templates/blog.jinja2
{% extends "home_layout.jinja2" %}
{% block layout %}
    {% if is_authenticated %}
        <div id="blog-trigger"
                hx-trigger="load"
                hx-get="/cms_blog"
                hx-target="#blog-container"
                hx-swap="innerHTML">
        </div>
        <div id="blog-container">
            
        </div>
    {% else %}
        <div id="blog-trigger"
                hx-trigger="load"
                hx-get="/login"
                hx-target="#blog-container"
                hx-swap="innerHTML">
        </div>

        <div id="blog-container">
        </div>
    {% endif %}
{% endblock %}

app/home/templates/home.jinja2
{% extends "home_layout.jinja2" %}
{% block layout %}

<div id="home">

    <header class="text-left">
        <h1 class="text-4xl font-bold">Welcome to My World</h1>
        <p class="text-xl mt-2">
            Welcome to my personal portfolio and blog. Here, you'll find a showcase of my projects, 
            my journey as a web developer, and my thoughts shared through my blog. I specialize in creating dynamic, 
            user-friendly websites using Flask, HTMX, and Tailwind.
        </p>
    </header>

    <section class="mt-4">
        <h2 class="text-3xl font-semibold mb-4">Featured Projects</h2>
        <p>Discover my recent work including various web applications, collaborations,
         and personal projects. Each project highlights my skills in different aspects of web development.</p>
        <!-- You can add a list or gallery of projects here -->
    </section>

    <section class="mt-8">
        <p class="text-gray-400">
        Interested in blogging? Join our community!<a href="/signup" class="text-gray-100"> Sign up today!</a></p>
        <!-- Link to the login or sign-up page -->
    </section>

</div>
{% endblock %}

app/home/templates/home_layout.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Datakiin</title>
    <meta name="Datakiin" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Place the first <script> tag in your HTML's <head> -->
    {% assets 'css' %}
      <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}

    
</head>
<body class="overflow-hidden h-screen">
  <header class="bg-black text-white py-6">
        <div class="container text-center">
            <h1 class="text-4xl font-bold">DATAKIIN</h1>
        </div>
    </header>
    
    <nav class="bg-black text-white">
        <div class="container" id="nav">
            <div class="navbar border-t border-b border-gray-300 pt-2 pb-2 flex justify-between ">
            {% include "/nav_default.jinja2" %}
            </div>
        </div>
    </nav>

    <div class="container overflow-auto h-[60vh]" id="hero">
        {% block layout %}{% endblock %}
    </div>

    <footer class="text-center mt-3">
        <p>Get in touch at <a href="mailto:jon.gracias@gmail.com" class="text-blue-500">jon.gracias@gmail.com</a></p>
        <a href="https://github.com/datakiin-core" class="inline-block mt-2" >
        GITHUB
        </a>
        |
        <a href="https://www.linkedin.com/in/jonathan-gracias-perez-b7577656" class="inline-block mt-2">
        LINKEDIN
        </a>
        |
        <a href="/phone" class="inline-block mt-2">
        PHONE
        </a>
    </footer>

  {% assets "js_home" %}
      <script type="text/javascript" src="{{ ASSET_URL }}"></script>
  {% endassets %}
</body>
</html>

app/home/templates/projects.jinja2
{% extends "home_layout.jinja2" %}
{% block layout %}
    <div id="projects">

        <div class="project-card">
            <h1 class="text-6xl">Blog</h1>
            <div class="mx-auto max-w-prose">
                <p class="text-base md:text-lg lg:text-xl font-normal text-gray-700 dark:text-gray-300 leading-relaxed my-4">
                    By: Jon Gracias
                </p>
                <p class="text-base md:text-lg lg:text-xl font-normal text-gray-700 dark:text-gray-300 leading-relaxed my-4">
                    Blogs can cover a wide range of topics, from personal life and hobbies to highly specialized subjects. 
                    They can be an effective platform for individuals or organizations to establish an online presence, 
                    share insights, and engage with a broader audience.
                </p>
                <a class="text-base md:text-lg lg:text-xl font-normal text-gray-700 dark:text-gray-300 leading-relaxed my-4 text-right block" href="/blog">Go to Blog</a>
            </div>
        </div>

    </div>
{% endblock %}